language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['cmake', 'clang-3.8', 'libstdc++-6-dev']
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
      env: COMPILER='clang++-3.8'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}

    # Use Debug builds for building and running examples
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -DPISTACHE_BUILD_EXAMPLES=true -DPISTACHE_BUILD_TESTS=true

    # Release build
  - cmake -H. -BBuild-Release -DCMAKE_BUILD_TYPE=Release

script:
  - # Go to debug build
  - cd Build-Debug
  - make -j 2 all test ARGS="-V"
  - # Go to release build
  - cd ../Build-Release
  - make -j 2
