language: cpp

branches:
  only:
    - master

matrix:
  include:
    # Linux clang builds
    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['cmake', 'clang-4.0', 'libstdc++-6-dev']
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
      env: COMPILER='clang++-4.0'
    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['cmake', 'clang-5.0', 'libstdc++-6-dev']
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
      env: COMPILER='clang++-5.0'
    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['cmake', 'clang-6.0', 'libstdc++-6-dev']
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
      env: COMPILER='clang++-6.0'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}

    # Use Debug builds for building and running examples
  - cmake -H. -BBuild-Debug -DCMAKE_BUILD_TYPE=Debug -DPISTACHE_BUILD_EXAMPLES=true -DPISTACHE_BUILD_TESTS=true

    # Release build
  - cmake -H. -BBuild-Release -DCMAKE_BUILD_TYPE=Release

script:
  - # Go to debug build
  - cd Build-Debug
  - make -j 2 all test ARGS="-V"
  - # Go to release build
  - cd ../Build-Release
  - make -j 2
